-- MySQL Script generated by MySQL Workbench
-- Fri Apr 21 10:12:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Phone_payments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Phone_payments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Phone_payments` DEFAULT CHARACTER SET utf8 ;
USE `Phone_payments` ;

-- -----------------------------------------------------
-- Table `Phone_payments`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Phone_payments`.`Payments` (
  `Payment_Id` INT NOT NULL AUTO_INCREMENT,
  `Phone_num` VARCHAR(10) NULL,
  `Payment_date` DATE NULL,
  `Local_paid` DECIMAL(9,2) NULL,
  `Long_dist_paid` DECIMAL(9,2) NULL,
  `Paid_account` INT NOT NULL,
  PRIMARY KEY (`Payment_Id`),
  INDEX `SubsAcc` (`Paid_account` ASC, `Phone_num` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Phone_payments`.`Subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Phone_payments`.`Subscribers` (
  `Subscriber_Id` INT NOT NULL AUTO_INCREMENT,
  `Subscriber_name` VARCHAR(128) NOT NULL,
  `Phone_num` VARCHAR(10) NOT NULL,
  `Tariff_code` INT NOT NULL,
  PRIMARY KEY (`Subscriber_Id`),
  INDEX `SubsAcc` (`Subscriber_Id` ASC, `Phone_num` ASC) INVISIBLE,
  INDEX `TarCod` (`Tariff_code` ASC) VISIBLE,
  CONSTRAINT `SubsAcc`
    FOREIGN KEY (`Subscriber_Id` , `Phone_num`)
    REFERENCES `Phone_payments`.`Payments` (`Paid_account` , `Phone_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Phone_payments`.`Tariffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Phone_payments`.`Tariffs` (
  `Tariff_Id` INT NOT NULL AUTO_INCREMENT,
  `Benef_cat` VARCHAR(45) NOT NULL,
  `Local_cost` DECIMAL(9,2) NOT NULL,
  `Long_cost` DECIMAL(9,2) NOT NULL,
  `International_cost` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`Tariff_Id`),
  INDEX `TarCod` (`Tariff_Id` ASC) VISIBLE,
  CONSTRAINT `TarCod`
    FOREIGN KEY (`Tariff_Id`)
    REFERENCES `Phone_payments`.`Subscribers` (`Tariff_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Phone_payments`.`Payments`
-- -----------------------------------------------------
START TRANSACTION;
USE `Phone_payments`;
INSERT INTO `Phone_payments`.`Payments` (`Payment_Id`, `Phone_num`, `Payment_date`, `Local_paid`, `Long_dist_paid`, `Paid_account`) VALUES (1, '075943764', '29.01.23', 300, 45, 01);
INSERT INTO `Phone_payments`.`Payments` (`Payment_Id`, `Phone_num`, `Payment_date`, `Local_paid`, `Long_dist_paid`, `Paid_account`) VALUES (2, '084862124', '18.01.23', 257, 37, 02);
INSERT INTO `Phone_payments`.`Payments` (`Payment_Id`, `Phone_num`, `Payment_date`, `Local_paid`, `Long_dist_paid`, `Paid_account`) VALUES (3, '094745571', '12.01.23', 50, 26, 03);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Phone_payments`.`Subscribers`
-- -----------------------------------------------------
START TRANSACTION;
USE `Phone_payments`;
INSERT INTO `Phone_payments`.`Subscribers` (`Subscriber_Id`, `Subscriber_name`, `Phone_num`, `Tariff_code`) VALUES (01, 'Іванов Іван Іванович', '075943764', 64842184);
INSERT INTO `Phone_payments`.`Subscribers` (`Subscriber_Id`, `Subscriber_name`, `Phone_num`, `Tariff_code`) VALUES (02, 'Сергіїв Сергій Сергійович', '084862124', 98848713);
INSERT INTO `Phone_payments`.`Subscribers` (`Subscriber_Id`, `Subscriber_name`, `Phone_num`, `Tariff_code`) VALUES (03, 'Василів Василь Васильович', '094745571', 99745447);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Phone_payments`.`Tariffs`
-- -----------------------------------------------------
START TRANSACTION;
USE `Phone_payments`;
INSERT INTO `Phone_payments`.`Tariffs` (`Tariff_Id`, `Benef_cat`, `Local_cost`, `Long_cost`, `International_cost`) VALUES (1, 'Standart', 300, DEFAULT, DEFAULT);
INSERT INTO `Phone_payments`.`Tariffs` (`Tariff_Id`, `Benef_cat`, `Local_cost`, `Long_cost`, `International_cost`) VALUES (2, 'For_Veterans', 230, DEFAULT, DEFAULT);
INSERT INTO `Phone_payments`.`Tariffs` (`Tariff_Id`, `Benef_cat`, `Local_cost`, `Long_cost`, `International_cost`) VALUES (3, 'For_Invalids', 190, DEFAULT, DEFAULT);
INSERT INTO `Phone_payments`.`Tariffs` (`Tariff_Id`, `Benef_cat`, `Local_cost`, `Long_cost`, `International_cost`) VALUES (4, 'For_Chernobl', 190, DEFAULT, DEFAULT);
INSERT INTO `Phone_payments`.`Tariffs` (`Tariff_Id`, `Benef_cat`, `Local_cost`, `Long_cost`, `International_cost`) VALUES (4, 'For_Migrants', 210, DEFAULT, DEFAULT);
INSERT INTO `Phone_payments`.`Tariffs` (`Tariff_Id`, `Benef_cat`, `Local_cost`, `Long_cost`, `International_cost`) VALUES (5, 'For_Large_familys', 180, DEFAULT, DEFAULT);

COMMIT;

